# -*- mode: ruby -*-
# vi: set ft=ruby :
## vagrant plugins required:
# vagrant-digitalocean, vagrant, vagrant-hosts, vagrant-cachier
Vagrant.configure("2") do |config|

  # https://vagrantcloud.com/ubuntu/boxes/trusty64
  config.vm.box = "puppetlabs/ubuntu-14.04-64-puppet"

  # If you want to use vagrant-cachier,
  # please install vagrant-cachier plugin.
  if Vagrant.has_plugin?("vagrant-cachier")
    config.cache.enable :apt
  end

  config.vm.provider :virtualbox do |vb, override|
    # Use VBoxManage to customize the VM. For example to change memory:
    vb.customize ["modifyvm", :id, "--memory", "#{1024*2}"]
    vb.customize ["modifyvm", :id,  "--cpus",  "2"]

    # Please customize hostname and private ip configuration if you needed.
    override.vm.hostname = "mesos"
    private_ip = "192.168.33.10"
    override.vm.network :private_network, ip: private_ip
    override.vm.provision :hosts do |provisioner|
      provisioner.add_host private_ip , [ config.vm.hostname ]
    end

    # for mesos web UI.
    override.vm.network :forwarded_port, guest: 5050, host: 5050
    # for Marathon web UI
    override.vm.network :forwarded_port, guest: 8080, host: 8080
    # for Chronos web UI
    override.vm.network :forwarded_port, guest: 8081, host: 8081

    override.vm.provision :shell do |s|
      s.path = "scripts/populate_ssh_key.sh"
      s.args = "/home/vagrant vagrant"
    end
  end

  config.vm.provider :digitalocean do |digitalocean, override|
  end

  config.vm.provision "puppet" do |puppet|
    puppet.manifests_path    = "../manifests"
    puppet.module_path       = "../modules"
    puppet.manifest_file     = "site.pp"
    puppet.hiera_config_path = "../hiera.yaml"
    puppet.options           = "--verbose --debug"
  end

  #if zk?(ninfo[:hostname]) then
  #  myid = (/zk([0-9]+)/.match ninfo[:hostname])[1]
  #  cfg.vm.provision :shell, :inline => <<-SCRIPT
  #    sudo mkdir -p /tmp/zookeeper
  #    sudo chmod 755 /tmp/zookeeper
  #    sudo chown zookeeper /tmp/zookeeper
  #    sudo -u zookeeper echo #{myid} > /tmp/zookeeper/myid
  #    sudo -u zookeeper /opt/chef/embedded/bin/ruby /vagrant/scripts/gen_zoo_conf.rb > /etc/zookeeper/conf/zoo.cfg
  #    sudo restart zookeeper
  #  SCRIPT
  #end

  #config.vm.provision :shell, :privileged => true, :inline => <<-SCRIPT
    #mkdir -p /var/log/marathon
    #kill -KILL `ps augwx | grep marathon | tr -s " " | cut -d' ' -f2`
    #nohup /opt/marathon/bin/start --master zk://localhost:2181/mesos --zk_hosts localhost:2181 > /var/log/marathon/nohup.log 2> /var/log/marathon/nohup.log < /dev/null &

    # Install and run Chronos based on:
    # https://mesosphere.io/learn/run-chronos-on-mesos/
    #mkdir -p /var/log/chronos
    #nohup /opt/chronos/bin/start-chronos.bash --master zk://localhost:2181/mesos --zk_hosts zk://localhost:2181/mesos --http_port 8081 > /var/log/chronos/nohup.log 2> /var/log/chronos/nohup.log < /dev/null &
    #SCRIPT

    # If you wanted use `.dockercfg` file
    # Please place the file simply on this directory
    if File.exist?(".dockercfg")
      config.vm.provision :shell, :priviledged => true, :inline => <<-SCRIPT
        cp /vagrant/.dockercfg /root/.dockercfg
        chmod 600 /root/.dockercfg
        chown root /root/.dockercfg
        SCRIPT
    end
  #end
end
