#!/bin/bash
# ### BEGIN INIT INFO
# # Provides:          marathon
# # Required-Start:    $local_fs $remote_fs $network $syslog
# # Required-Stop:     $local_fs $remote_fs $network $syslog
# # Default-Start:     2 3 4 5
# # Default-Stop:      0 1 6
# # Short-Description: Init for Apache Mesos
# # Description:       Cluster-wide init and control system for Apache Mesos
# ### END INIT INFO
set -ue

# Source function library.
. /etc/rc.d/init.d/functions

NAME="marathon"
DESC="marathon"
marathonExec="/usr/local/bin/$NAME"
outFile="/var/log/marathon/$NAME.out"

if ! [ -f $marathonExec ]; then
  echo "$NAME binary not found."
  exit 5
fi

if [ -f /etc/sysconfig/$NAME ]; then
  . /etc/sysconfig/$NAME
fi


start() {
  echo -n $"Starting $desc ($NAME): "
  nohup $marathonExec --quiet >>$outFile 2>&1 &
  RETVAL=$?
  return $RETVAL  
}

stop() {
  echo -n $"Stopping $NAME: "
  pkill -f $marathonExec
}

status() {
  if [ -z $pid ]; then
     pid=$(pgrep -f $marathonExec)
  fi

  if [ -z $pid ]; then
    echo "$NAME is NOT running."
    return 1
  else
    echo "$NAME is running (pid is $pid)."
  fi

}

case "${1-}" in
  start)
    echo -n "Starting $DESC: "
    start
    echo "$NAME."
    ;;
  stop)
    echo -n "Stopping $DESC: "
    stop
    echo "$NAME."
    ;;
  restart)
    echo -n "Restarting $DESC: "
    stop
    sleep 1
    start
    echo "$NAME."
    ;;
  status)
    status;;
  *)
    echo "Usage: $0 {start|stop|restart|status}" >&2
    exit 1
    ;;
esac
